export const propieState = {
  titulo: "",
  descripcion: "",
  tipo: {code: '', name:''},
  direccion: "",
  ciudad: "",
  estado: "",
  precio: 0,
  habitaciones: 0,
  banos: 0,
  agente_id: {code: '', name:''},
  zona_comun: "",
  cocina: "",
  ropas: "",
  parqueadero: false,
  unidad: "",
  barrio: "",
  comuna: "",
  observaciones: ""
};